### ISSUE TITLE
HACKMIT error

### ISSUE THREAD

**Issue by code-arman** [juliustao/news-balance#1]
Lol, im not sure why but your stuff shows up apart of my team. This is really random. I screenhotted ur info so you dont lose it. Im going to delete your stuff and put the stuff for my project. I think HackMIT messed up spectacle 

![Screen Shot 2020-09-19 at 11 36 59 PM](https://user-images.githubusercontent.com/46976119/93705316-1c696700-fad1-11ea-97ab-f3bf8073d88e.png)

**Comment by juliustao** [comment]
Thanks for letting me know Arman. I unfortunately went to sleep without seeing this message and woke up this morning right before judging, so I didn't see that it was deleted until past the submission deadline. I'll resubmit and pray that the late entry still goes through

**Comment by juliustao** [comment]
Update: Naturally, my submission was missing from their database because of the deletion circumstances. I eventually got in direct contact with a HackMIT staff member to manually add my project, so I eventually got to present my project to judges.
